apiVersion: v1
kind: PersistentVolume
metadata:
  name: travel-postgres-pv
spec:
  capacity:
    storage: {{ .Values.postgres.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storage.className }}
  hostPath:
    path: /data/travel-postgres