apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: travel-postgres-pvc
  namespace: {{ .Values.namespace }}

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storage.className }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}