apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: travel-postgres-pvc
  namespace: travel-planner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: travel-storage-class
  resources:
    requests:
      storage: 1Gi