apiVersion: v1
kind: PersistentVolume
metadata:
  name: travel-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: travel-storage-class
  hostPath:
    path: /data/travel-postgres